
DROP TABLE IF EXISTS partida;
DROP TABLE IF EXISTS inscrit;
DROP TABLE IF EXISTS grup;
DROP TABLE IF EXISTS torneig;
DROP TABLE IF EXISTS estadistica_modalitat;
DROP TABLE IF EXISTS modalitat;
DROP TABLE IF EXISTS soci;